import { ReactComponent as ExitIcon } from './svg-logout.svg';
import { ReactComponent as HangerIcon } from './svg-hanger.svg';
import { ReactComponent as BinIcon } from './svg-bin.svg';
import { ReactComponent as PenIcon } from './svg-pen.svg';
import { ReactComponent as ArrowIcon } from './svg-arrow.svg';
import { ReactComponent as ClosetIcon } from './svg-closet.svg';
import { ReactComponent as OutfitsIcon } from './svg-outfits.svg';
import { ReactComponent as PlusIcon } from './svg-plus.svg';
import { ReactComponent as AddItemIcon } from './svg-add-item.svg';
import { ReactComponent as XIcon } from './svg-x.svg'; 
import { ReactComponent as QuestionIcon } from './svg-question.svg'; 
import { ReactComponent as HeartIcon } from './svg-heart.svg';
import { ReactComponent as PlanetIcon } from './svg-planet.svg'; 
import { ReactComponent as TimeIcon } from './svg-time.svg'; 
import { ReactComponent as MoneyIcon } from './svg-money.svg'; 
import { ReactComponent as LinkedinIcon } from './svg-linkedin.svg'; 
import { ReactComponent as GithubIcon } from './svg-github.svg'; 
import { ReactComponent as AlgoIcon } from './svg-algo.svg'; 
export { ExitIcon };
export { HangerIcon };
export { PenIcon };
export { BinIcon };
export { ArrowIcon };
export { ClosetIcon };
export { OutfitsIcon }
export { PlusIcon };
export { AddItemIcon };
export { XIcon };
export { QuestionIcon };
export { HeartIcon };
export { PlanetIcon };
export { TimeIcon };
export { MoneyIcon };
export { LinkedinIcon };
export { GithubIcon };
export { AlgoIcon };